'use strict';
export const REQUEST_HOTWORD = "REQUEST_HOTWORD";
export const RESPONSE_HOTWORD = "RESPONSE_HOTWORD";

export const REQUEST_SINGLERECOMMEND = "REQUEST_SINGLERECOMMEND";
export const RESPONSE_SINGLERECOMMEND = "RESPONSE_SINGLERECOMMEND";
export const REQUEST_NEWRECOMMEND = "REQUEST_NEWRECOMMEND";
export const RESPONSE_NEWRECOMMEND = "RESPONSE_NEWRECOMMEND";