'use strict';

export const CHANGE_FIELD = "CHANGE_FIELD";
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const SHOW_ACTIVITYINDICATOR = "SHOW_ACTIVITYINDICATOR";
export const HIDE_ACTIVITYINDICATOR = "HIDE_ACTIVITYINDICATOR";

export const CHANGE_SCENE = "CHANGE_SCENE"
