'use strict';

export const REQUEST_SHIPFEE = "REQUEST_SHIPFEE";
export const RESPONSE_SHIPFEE = "RESPONSE_SHIPFEE";

export const START_SUBMITORDER = "START_SUBMITORDER";
export const FINISH_SUBMITORDER = "FINISH_SUBMITORDER";
export const CHANGE_COUPON = "CHANGE_COUPON";
export const CHANGE_RECEIVER = "CHANGE_RECEIVER";

export const REQUEST_PAYGATEWAY = "REQUEST_PAYGATEWAY";
export const RESPONSE_PAYGATEWAY = "RESPONSE_PAYGATEWAY";
