'use strict';

export const REQUEST_CATEGORYBRANDS = "REQUEST_CATEGORYBRANDS";
export const RESPONSE_CATEGORYBRANDS = "RESPONSE_CATEGORYBRANDS";
export const REQUEST_ALLBRANDS = "REQUEST_ALLBRANDS";
export const RESPONSE_ALLBRANDS = "RESPONSE_ALLBRANDS";
export const REQUEST_ALLORIGINS = "REQUEST_ALLORIGINS";
export const RESPONSE_ALLORIGINS = "RESPONSE_ALLORIGINS";