export const START_FETCH_COUPON = "START_FETCH_COUPON";
export const FINISH_FETCH_COUPON = "FINISH_FETCH_COUPON";
export const START_FETCH_DETAIL="START_FETCH_DETAIL";
export const FINISH_FETCH_DETAIL="FINISH_FETCH_DETAIL";
//export const FETCH_COUPON_ID = "FETCH_COUPON_ID";