export const START_UPDATE_CART = "START_UPDATE_CART";
export const FINISH_UPDATE_CART = "FINISH_UPDATE_CART";

export const START_DELETE_CART = "START_DELETE_CART";
export const FINISH_DELETE_CART = "FINISH_DELETE_CART";

export const START_TOGGLE_ITEM = "START_TOGGLE_ITEM";
export const FINISH_TOGGLE_ITEM = "FINISH_TOGGLE_ITEM";

export const START_TOGGLE_ALL = "START_TOGGLE_ALL";
export const FINISH_TOGGLE_ALL= "FINISH_TOGGLE_ALL";

export const CHANGE_CART_NUM = "CHANGE_CART_NUM";

 