export const START_DELETE_IDCARD = "START_DELETE_IDCARD";
export const FINISH_DELETE_IDCARD = "FINISH_DELETE_IDCARD";

export const START_UPDATE_IDCARD="START_UPDATE_IDCARD";
export const FINISH_UPDATE_IDCARD="FINISH_UPDATE_IDCARD";

export const START_ADD_IDCARD="START_ADD_IDCARD";
export const FINISH_ADD_IDCARD="FINISH_ADD_IDCARD";

export const START_UPLOAD_IDCARD="START_UPLOAD_IDCARD";
export const FINISH_UPLOAD_IDCARD="FINISH_UPLOAD_IDCARD";
